import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactQueryProvider from "./contexts/ReactQueryProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import "./globals.css";
import "react-loading-skeleton/dist/skeleton.css";
import Navbar from "./components/Navbar";
import Dock from "./components/Dock";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokedex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <Navbar />
          {children}
          <Dock />
          {/* <ReactQueryDevtools /> */}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
